require: rubocop-rails

AllCops:
  Exclude:
    - "**/vendor/**/*"
    - "**/*.gemspec"
    - "bin/**/*"
    - "config/environments/**/*"
    - "config/initializers/devise.rb"
    - "db/**/*"
    - "spec/**"
  NewCops: enable
  TargetRubyVersion: 3.0.1
  SuggestExtensions: false

Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/AsciiComments:
  Enabled: false
